---
abstract: 'Perl interface to twitter.com'
author:
  - 'Chris Thompson <cpan@cthompson.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Twitter
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  JSON::Any: 1.19
  LWP::UserAgent: 2.032
  URI::Escape: 0
  perl: 5.005
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Twitter
  homepage: http://www.net-twitter.info
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ct/net-twitter.git
version: 2.12
