--- #YAML:1.0
name:               Win32-SerialPort
version:            0.22
abstract:           User interface to Win32 Serial API calls
author:
    - Bill Birthisel <wcbirthisel@alum.mit.edu>
license:            Perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
    Win32:       0
    Win32::API:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
